### ISSUE TITLE
Ray ml docker image not found

### ISSUE THREAD

**Issue by allamand** [aws-samples/gen-ai-on-eks#7]
The image described in the `ray_serve_manifests/00_ray_serve_fine_tuned.yaml` file points to a docker tag that does not want to be downloaded: 

``` 
docker pull rayproject/ray-ml:2.6.3.54de39-py38-cpu
Error response from daemon: manifest for rayproject/ray-ml:2.6.3.54de39-py38-cpu not found: manifest unknown: manifest unknown
```

Even if the tag seems to properly exists in docker hub.
Using a more general ones seems to work like : `rayproject/ray-ml:2.6.3-py38-gpu`

that may be an issue on docker hub side

**Comment by lusoal** [comment]
Fixed on #9
